### ISSUE TITLE
Error: public.list_postgres_log_file() not found.

### ISSUE THREAD

**Issue by arqgroup-rohits** [aws-samples/amazon-rds-and-amazon-aurora-logging-blog#3]
Engine version: 11.13
Error:
ERROR:  function public.list_postgres_log_files() does not exist
LINE 1: SELECT file_name FROM public.list_postgres_log_files() WHERE...
                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT file_name FROM public.list_postgres_log_files() WHERE file_name LIKE '%.csv' ORDER BY 1 DESC
CONTEXT:  PL/pgSQL function load_postgres_log_files(text,text,boolean) line 56 at FOR over EXECUTE statement

I know the documentation says you need v12 for PostGres, but is that for this Function to work as well? or just to enable pg_cron?
https://aws.amazon.com/blogs/database/automate-postgresql-log-exports-to-amazon-s3-using-extensions/
Really not sure what enables this function, the documentation doesn't suggest that we create this function too.

**Comment by yrraja** [comment]
Please confirm that you have set up the log_fdw extension before installing this function. Here are the instructions to set it up:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Extensions.foreign-data-wrappers.html#CHAP_PostgreSQL.Extensions.log_fdw

From the error it looks like you missed the following step after creating the extension:
    CREATE SERVER log_server FOREIGN DATA WRAPPER log_fdw;
